@startuml
!include <C4/C4_Deployment.puml>

HIDE_STEREOTYPE()
LAYOUT_TOP_DOWN()

title Test RabbitMQ (Dataflow Diagram)

Node(rabbitmqserver, "RabbitMQ Server Docker", "RedHat", Docker container) {
     
    Container(rabbitmqserver_listeners, "Java Bridge PLC [1-7]", "Java JRE 17", "/opt/jprogram/start_listener.sh")
    
    Node(rabbitmqserver_rabbitmqbroker, "RabbitMQ Broker", "RabbitMQ 3.0", MsgContainer) {
        ContainerQueue(rabbitmqserver_rabbitmqbroker_toplc, "ToPLC[1-19]", "Queue")
        ContainerQueue(rabbitmqserver_rabbitmqbroker_fromplc, "FromPLC[1-19]", "Queue")
        Container(rabbitmqserver_rabbitmqbroker_monitor, "RabbitMQ monitor manager")
    }
}

Container(plcsimulator, "PLC simulator Docker", "Python", "Channel 80[1-19]")

Container(prometheusserver, "Prometheus server Docker", "Redhat", "Prometheus")

Container(wcsserver, "WCS server Docker", "PLC [1-7]", "Progress 4gl")

Rel_U(rabbitmqserver_listeners, rabbitmqserver_rabbitmqbroker_fromplc, "sends to")
Rel_U(rabbitmqserver_listeners, rabbitmqserver_rabbitmqbroker_toplc, "receives from")

Rel_U(wcsserver, rabbitmqserver_rabbitmqbroker_toplc, "sends to") 
Rel_U(wcsserver, rabbitmqserver_rabbitmqbroker_fromplc, "receives from") 
Rel_U(rabbitmqserver_rabbitmqbroker_monitor, prometheusserver, "sends to")
BiRel(plcsimulator, rabbitmqserver_listeners, "sends to", "receives from")

@enduml